### ISSUE TITLE
Error when launching kobuki_slam

### ISSUE THREAD

**Issue by Neykah** [bus710/sulcata#4]
Thank you for your work.
I have a functional libfreenect2 / iai_kinect2 installation, but I have difficulties to run kobuki_slam.
When I call : 

> roslaunch kobuki_slam kobuki_slam.launch

I get this error : 

> [ERROR] [1509445234.825467518]: Error connecting to Hokuyo: Could not open serial Hokuyo:
/dev/ttyACM0 @ 115200
could not open serial device.

I am using kinetic and  I have checked that map-server and move-base where both installed. I have also modified kobuki_slam.launch as you mentionned.
Do you have any idea on why I get this error ? Should I ask directly on the kobuki_slam git ?
Thank you in advance.

**Comment by bus710** [comment]
Hi,

@Neykah, as far as I know, it might be the xml configuration but I don't have the setting right now so that it is hard to reproduce. If you don't mind please contact the kobuki_slam git. Or ROS community group might be a good place to discuss.

**Comment by Neykah** [comment]
Hi, 
Thank you for answering.
For my part I think I will use rtabmap [http://wiki.ros.org/rtabmap_ros#rtabmap](url) instead of kobuki_slam for the SLAM operation. They submitted example launch files for compatibility with freenect2 / kinect2bridge, which make it simple to use and learn for a ROS beginner like me.
Just wanted to mention it for the record if somebody else happen to struggle with that kind of configuration.
